name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Checkout project sources
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Get Java version
        run: java --version
      - name: Run build with Gradle Wrapper
        run: ./gradlew build publish --exclude-task test -i -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}
      - name: Upload JUnit Report
        uses: actions/upload-artifact@v3
        if: always()
        continue-on-error: true
        with:
          name: Test Report
          path: build/reports/tests/test/
