name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: "Set up latest Oracle JDK 20"
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Get Java version
        run: java --version
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
